import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Roboto_Mono, Montserrat as Font_Montserrat } from 'next/font/google'
import Footer from "@/components/Footer";
import '../styles/scrollbar.css'
import DisableInspect from "@/components/DisableInspect";
import PageTransitionWrapper from "@/components/PageTransitionWrapper";

const roboto = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto', // optional: for using as CSS variable
  display: 'swap',
})

const montserrat = Font_Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="   ">
      <head>

      </head>
      <body
        className={`${roboto.variable} ${montserrat.variable}`}
      >
        <PageTransitionWrapper >
          <DisableInspect />
          <Navbar />
          {children}
          <Footer />
        </PageTransitionWrapper>
      </body>
    </html>
  );
}
